{"name": "test_random", "status": "failed", "statusDetails": {"message": "AssertionError: Assertion failed, Expected 7\nassert (5 + 2) == 2", "trace": "def test_random():\n        x = 5\n        y = 2\n        assert x + y == 7, \"Assertion failed, Expected 7\"\n>       assert x + y == 2, \"Assertion failed, Expected 7\"\nE       AssertionError: Assertion failed, Expected 7\nE       assert (5 + 2) == 2\n\npytest_project\\random_name_file_test.py:7: AssertionError"}, "start": 1669994098088, "stop": 1669994098088, "uuid": "fb8087f2-c5e4-4344-8060-14a6b67e9c97", "historyId": "fc53104267274491dca0566c78a8e712", "testCaseId": "18b6db6c2a0f25434ffeb09922872a90", "fullName": "pytest_project.random_name_file_test#test_random", "labels": [{"name": "parentSuite", "value": "pytest_project"}, {"name": "suite", "value": "random_name_file_test"}, {"name": "host", "value": "DESKTOP-OM28FAJ"}, {"name": "thread", "value": "7416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_project.random_name_file_test"}]}